spring:
  profiles:
    active: test
   
---
server:
 port: 8001
  
spring:
 profiles: dev
  application: 
   name: cloud-dev-1.0
 
---
spring:
  profiles: test
  application: 
    name: cloud-dev-test-1.0
 
 
 
